### ISSUE TITLE
Powershell config DISABLE_32/64BIT does not work

### ISSUE THREAD

**Issue by Doridian** [danielga/garrysmod_common#107]
PowerShell (unlike bash) separates environment from other variables.
So setting `DISABLE_64BIT = "true"` as an environment variable does in fact not propagate into `$DISABLE_64BIT` but only into `$env:DISABLE_64BIT`.
Or are those variables supposed to be set in another way?

In my PR I had the `$env:` because I intended this to work with env vars initially.

**Comment by danielga** [comment]
Where and how are you setting `DISABLE_64BIT`? It seems like you're setting script variables (`DISABLE_64BIT = "true"` instead of `$env:DISABLE_64BIT = "true"`), and like you said, those don't get shared between scripts.

If you look at [build/setup.ps1](https://github.com/danielga/garrysmod_common/blob/e39387e644b081a629d151334de18ee856233c89/build/setup.ps1), you'll see calls to `ValidateVariableOrSetDefault`, which gets the value from the environment variable and copies it into the script variable.

**Comment by Doridian** [comment]
I am setting them as env vars like such: https://github.com/SpaceAgeMP/gm_enginespew/blob/main/.github/workflows/build.yml#L57

And yet the build tries to build 64-bit binaries: https://github.com/SpaceAgeMP/gm_enginespew/actions/runs/8591446795/job/23540220031#step:3:139

**Comment by danielga** [comment]
Argh, I think I screwed up the PowerShell script `build.ps1`. Any way you can test changes to it? I believe the error is in this line `if (ValueIsFalsy $DISABLE_64BIT && $PROJECT_GENERATOR_VERSION -ge 3) {`. `&&` is not the same as the logical operator `-and` 🤦. Even though `ValueIsFalsy $DISABLE_64BIT` is returning false, the `if` conditional is passing because of that `&&`.

**Comment by danielga** [comment]
Just pushed a commit with that fix. I tested it locally and it seemed to work.

**Comment by Doridian** [comment]
@danielga Just tested your suggested change and it works for the enginespew build. 

And also just tested your latest push and it now fully builds on everything. Thanks for the quick fix.
