### ISSUE TITLE
Linux GCC Predefined macros

### ISSUE THREAD

**Issue by Weeabooru** [danielga/garrysmod_common#12]
Please notice users that without this macros
```
-DPOSIX -DLINUX -DGAME_DLL -D__GNUC__ -D__GCC__ -DGNUC	\
	-D_LINUX  -std=c++11
```
nothing will works. Don't waste time, guys

**Comment by birdbrainswagtrain** [comment]
🤔

**Comment by danielga** [comment]
POSIX, LINUX, _LINUX and GNUC are all already defined on the Source SDK module.
-std=c++11 is the minimum required by garrysmod_common, it is defined at all times.
__GCC__ is useless because the only place where it's used also checks for __GNUC__.
__GNUC__ is defined by the compiler.
GAME_DLL should never be defined because that's for game DLLs and you don't have access to Garry's Mod source code, so you're setting yourself up for spectacular shows of fireworks (read: crashes).
